services:
  postgres:
    image: postgres:16-alpine
    container_name: personalagent-postgres-2
    environment:
      POSTGRES_DB: personalagent
      POSTGRES_USER: personalagent
      POSTGRES_PASSWORD: personalagent
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U personalagent -d personalagent"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: personalagent-redis-2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: personalagent-backend-2
    env_file:
      - ./backend/.env
    environment:
      ENVIRONMENT: development
      DATABASE_URL: postgresql+asyncpg://personalagent:personalagent@postgres:5432/personalagent
      APP_NAME: PersonalAgent API
      REDIS_URL: redis://redis:6379/0
      AGENT_BASE_URL: http://agent-service:8001
      BACKEND_CALLBACK_URL: http://backend:8000/api/agent/callback
      AGENT_REGISTRY_SECRET: change-agent-registry-secret
      UPLOAD_DIR: /app/storage/uploads
      OUTPUT_DIR: /app/storage/outputs
      MAX_PREVIEW_ROWS: 50
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      JWT_SECRET_KEY: change-this-before-production
    ports:
      - "8000:8000"
    volumes:
      - backend_storage:/app/storage
      - ./agent-framework/new-agentic-project-data-cleaning-/src:/app/finflow_agent_src
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      agent-service:
        condition: service_started

  agent-service:
    build:
      context: ./agent-framework/new-agentic-project-data-cleaning-
    env_file:
      - ./agent-framework/new-agentic-project-data-cleaning-/.env
    container_name: personalagent-agent-service-2
    environment:
      HOST: 0.0.0.0
      PORT: 8001
      DATABASE_URL: postgresql://personalagent:personalagent@postgres:5432/personalagent
      BACKEND_BASE_URL: http://backend:8000
      AGENT_REGISTRY_SECRET: change-agent-registry-secret
      ENABLE_LLM_PREDICATE_GROUNDING: "true"
      UPLOAD_DIR: /app/storage/uploads
      OUTPUT_DIR: /app/storage/outputs
      REDIS_URL: redis://redis:6379/0
      GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8001:8001"
    volumes:
      - backend_storage:/app/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: personalagent-frontend-2
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
  backend_storage:
